# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13DS3yWsrtUXi_w8Gu53TuHH_pORhEH2v
"""

#install and import matplotlib

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Commented out IPython magic to ensure Python compatibility.
#matplotlib to render plots in the notebook
# %matplotlib inline

x = np.arange (1,201,2)
y = np.random.randint(1,10,100)

plt.figure(figsize=(15,5))
plt.axes(facecolor='pink')
plt.plot(x, y,color='black', label='Line chart') #line chart
plt.xlim(0, 200)
plt.ylim(0, 10)
plt.xlabel('Sales')
plt.ylabel('product')
plt.title('Line Plot')
plt.suptitle('Sales Comparison', size=20, y=1.05)
plt.savefig('Save.png')
plt.legend()
plt.show()

fig, ax = plt.subplots(nrows=2, ncols=2)
ax[0,0].plot(x,y)
plt.title("plot 1")

plt.tight_layout()

df = pd.read_csv('/content/sample_data/california_housing_train.csv').dropna()
plt.figure (figsize=(10,10))
for i,j in enumerate(df.columns):
 # print(i,j)
  plt.subplot(15,3,i+1)
  plt.hist(df[j])
  plt.title(j)
  plt.tight_layout()



df.hist(figsize=(20,20))
plt.show()



"""Matplotlib"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

mtcars = pd.read_csv("https://raw.githubusercontent.com/slmsshk/DataSet/main/mtcars.csv")

mtcars.columns

mtcars.shape

mtcars.head()

mtcars.tail()

mtcars.describe()

mtcars.info()

#table
pd.crosstab(mtcars.gear,mtcars.cyl)


#Explanation Of This Output is 
#if we have 3 gear then we have 1 example with 4 cyl
#if we have 4 gear then we have 4 example with 6 cyl

mtcars.hist(figsize=(10,10), color='peru')
plt.show()

#barplot between 2 different categories
pd.crosstab(mtcars.gear, mtcars.cyl).plot(kind='bar')
plt.show()



